"""
Database utility functions
"""
from typing import Dict


def normalize_measure_data(data: dict) -> dict:
    """
    Normalize field names to match BallotMeasure model.

    This function standardizes various input formats from different scrapers
    and parsers to match the BallotMeasure dataclass fields.

    Args:
        data: Raw measure data dictionary from a scraper or parser

    Returns:
        Normalized dictionary with only valid BallotMeasure fields
    """
    normalized = data.copy()

    # Field name mappings
    if 'source' in normalized:
        normalized['data_source'] = normalized.pop('source')

    if 'measure_text' in normalized and 'title' not in normalized:
        normalized['title'] = normalized.pop('measure_text')

    # Ensure required fields exist (will be generated by model)
    normalized.setdefault('fingerprint', '')
    normalized.setdefault('measure_fingerprint', '')
    normalized.setdefault('content_hash', '')

    # List of valid BallotMeasure fields
    valid_fields = {
        'fingerprint', 'measure_fingerprint', 'content_hash',
        'measure_id', 'measure_letter', 'year', 'state', 'county', 'jurisdiction',
        'title', 'description', 'ballot_question',
        'yes_votes', 'no_votes', 'total_votes', 'percent_yes', 'percent_no',
        'passed', 'pass_fail',
        'measure_type', 'topic_primary', 'topic_secondary', 'category_type', 'category_topic',
        'data_source', 'source_url', 'pdf_url',
        'has_summary', 'summary_title', 'summary_text',
        'election_type', 'election_date', 'decade', 'century',
        'created_at', 'updated_at', 'last_seen_at', 'update_count',
        'is_active', 'is_duplicate', 'duplicate_type', 'master_id', 'merged_from',
        'related_measures', 'relationship_type',
        'briefing_text', 'fiscal_impact', 'pro_arguments', 'con_arguments',
        'proponents', 'opponents', 'endorsements',
        'research_status', 'research_depth', 'research_updated_at', 'research_sources',
    }

    # Remove any fields not in the model
    filtered = {k: v for k, v in normalized.items() if k in valid_fields}

    return filtered
